version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cs60_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    networks:
      - cs60_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: cs60_mysql
    restart: always
    environment:
      MYSQL_DATABASE: cs60_recruitment
      MYSQL_USER: cs60user
      MYSQL_PASSWORD: cs60password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - cs60_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cs60_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - cs60_network
    depends_on:
      - mysql

networks:
  cs60_network:

volumes:
  mysql_data:
